-- Generated by tools/export_tiger_sentence_rime.py. Do not edit.
local M = {}
M.codes = {
}
local length_set = {
  [1] = true,
  [2] = true,
  [3] = true,
  [4] = true,
}
local shards = {
  require("tiger_sentence_lexicon_01"),
  require("tiger_sentence_lexicon_02"),
  require("tiger_sentence_lexicon_03"),
  require("tiger_sentence_lexicon_04"),
  require("tiger_sentence_lexicon_05"),
  require("tiger_sentence_lexicon_06"),
  require("tiger_sentence_lexicon_07"),
  require("tiger_sentence_lexicon_08"),
}
for _, shard in ipairs(shards) do
  for code, candidates in pairs(shard) do
    M.codes[code] = candidates
  end
end
local ok, custom = pcall(require, "tiger_sentence_custom")
if not ok then
  local err = tostring(custom)
  if not err:find("module 'tiger_sentence_custom' not found", 1, true) then
    error(custom)
  end
  custom = {}
elseif type(custom) ~= "table" then
  custom = {}
end
for raw_code, candidates in pairs(custom) do
  local code = string.lower(raw_code)
  local normalized = {}
  for rank, candidate in ipairs(candidates) do
    if type(candidate) == "string" then
      normalized[#normalized + 1] = {t=candidate, r=rank}
    elseif type(candidate) == "table" and type(candidate.t) == "string" then
      normalized[#normalized + 1] = {t=candidate.t, r=candidate.r or rank}
    end
  end
  if #normalized == 0 then
    M.codes[code] = nil
  else
    M.codes[code] = normalized
    length_set[#code] = true
  end
end
M.lengths = {}
for length in pairs(length_set) do
  M.lengths[#M.lengths + 1] = length
end
table.sort(M.lengths)
return M
