# Included only with BUILD_TESTING. Geometry has no Windows or JSON dependency.
add_executable(overlay_placement_history_tests tests/PlacementHistoryTests.cpp)
target_include_directories(overlay_placement_history_tests PRIVATE ${CMAKE_CURRENT_SOURCE_DIR})
if(MSVC)
    target_compile_options(overlay_placement_history_tests PRIVATE /W4 /utf-8)
else()
    target_compile_options(overlay_placement_history_tests PRIVATE -Wall -Wextra -Wpedantic)
endif()
add_test(NAME overlay_placement_history COMMAND overlay_placement_history_tests)
if(WIN32)
    # Explicit execution only: creates nonactivating, test-owned layered HWNDs.
    # No production IPC, foreground activation, SendInput, registration or audio.
    add_executable(overlay_placement_publication_tests tests/PlacementPublicationTests.cpp Transport.cpp Sound.cpp)
    target_include_directories(overlay_placement_publication_tests PRIVATE ${CMAKE_CURRENT_SOURCE_DIR})
    target_include_directories(overlay_placement_publication_tests SYSTEM PRIVATE ../../third_party/llama.cpp/vendor)
    target_compile_definitions(overlay_placement_publication_tests PRIVATE UNICODE _UNICODE WIN32_LEAN_AND_MEAN NOMINMAX _WIN32_WINNT=0x0A00 WINVER=0x0A00)
    target_link_libraries(overlay_placement_publication_tests PRIVATE overlay_model d2d1 dwrite user32 gdi32 shell32 shcore ole32)
    if(MSVC)
        target_compile_options(overlay_placement_publication_tests PRIVATE /W4 /utf-8)
        target_link_libraries(overlay_placement_publication_tests PRIVATE xaudio2)
    else()
        target_link_libraries(overlay_placement_publication_tests PRIVATE xaudio2_9)
    endif()
endif()
