if(BUILD_TESTING)
    add_executable(overlay_pending_frame_policy_tests tests/PendingFramePolicyTests.cpp)
    add_test(NAME overlay_pending_frame_policy COMMAND overlay_pending_frame_policy_tests)
    if(WIN32)
        # Explicit nonactivating, test-owned HWNDs only; no live input or Core IPC.
        add_executable(overlay_pending_frame_tests tests/CandidateFrameHoldTests.cpp Transport.cpp Sound.cpp)
        target_include_directories(overlay_pending_frame_tests SYSTEM PRIVATE ../../third_party/llama.cpp/vendor)
        target_compile_definitions(overlay_pending_frame_tests PRIVATE UNICODE _UNICODE WIN32_LEAN_AND_MEAN NOMINMAX _WIN32_WINNT=0x0A00 WINVER=0x0A00)
        target_link_libraries(overlay_pending_frame_tests PRIVATE overlay_model d2d1 dwrite user32 gdi32 shell32 shcore ole32)
        if(MSVC)
            target_compile_options(overlay_pending_frame_tests PRIVATE /W4 /utf-8)
            target_link_libraries(overlay_pending_frame_tests PRIVATE xaudio2)
        else()
            target_link_libraries(overlay_pending_frame_tests PRIVATE xaudio2_9)
        endif()
    endif()
endif()
