if(BUILD_TESTING)
    add_executable(overlay_pending_frame_policy_tests tests/PendingFramePolicyTests.cpp)
    add_test(NAME overlay_pending_frame_policy COMMAND overlay_pending_frame_policy_tests)
    if(WIN32)
        # Explicit nonactivating, test-owned HWNDs only; no live input or Core IPC.
        function(pending_frame_target name source)
            add_executable(${name} "${source}" Transport.cpp Sound.cpp)
            target_include_directories(${name} PRIVATE "${CMAKE_CURRENT_SOURCE_DIR}")
            target_include_directories(${name} SYSTEM PRIVATE ../../third_party/llama.cpp/vendor)
            target_compile_definitions(${name} PRIVATE UNICODE _UNICODE WIN32_LEAN_AND_MEAN NOMINMAX _WIN32_WINNT=0x0A00 WINVER=0x0A00)
            target_link_libraries(${name} PRIVATE overlay_model d2d1 dwrite user32 gdi32 shell32 shcore ole32)
            if(MSVC)
                target_compile_options(${name} PRIVATE /W4 /utf-8)
                target_link_libraries(${name} PRIVATE xaudio2)
            else()
                target_link_libraries(${name} PRIVATE xaudio2_9)
            endif()
        endfunction()
        pending_frame_target(overlay_pending_frame_tests tests/CandidateFrameHoldTests.cpp)

        # Compile two regressions into deliberately broken production copies.
        # No mutation flags enter the shipped executable; no source files change.
        file(READ "${CMAKE_CURRENT_SOURCE_DIR}/main.cpp" original)
        file(READ "${CMAKE_CURRENT_SOURCE_DIR}/tests/CandidateFrameHoldTests.cpp" probe)
        foreach(control IN ITEMS no_session no_code_hold)
            set(mutated "${original}")
            if(control STREQUAL "no_session")
                set(gate "            ObserveCandidateSession();")
                string(FIND "${mutated}" "${gate}" found)
                if(found EQUAL -1)
                    message(FATAL_ERROR "Session observer changed; update negative control")
                endif()
                string(REPLACE "${gate}" "            // Test mutation: ignore session boundaries." mutated "${mutated}")
                set(gate "state_.candidateFrameSession.empty() ||\n                state_.candidateFrameSession != frameSession_ || ")
                string(FIND "${mutated}" "${gate}" found)
                if(found EQUAL -1)
                    message(FATAL_ERROR "Session hold gate changed; update negative control")
                endif()
                string(REPLACE "${gate}" "" mutated "${mutated}")
            else()
                set(gate "return display.mode != DisplayMode::Hidden && !display.text.empty();")
                string(FIND "${mutated}" "${gate}" found)
                if(found EQUAL -1)
                    message(FATAL_ERROR "Frame eligibility changed; update negative control")
                endif()
                string(REPLACE "${gate}" "return display.mode == DisplayMode::CandidatesOnly || display.mode == DisplayMode::CodeAndCandidates;" mutated "${mutated}")
            endif()
            set(source "${CMAKE_CURRENT_BINARY_DIR}/pending-${control}-probe.cpp")
            file(WRITE "${CMAKE_CURRENT_BINARY_DIR}/pending-${control}-main.cpp" "${mutated}")
            string(REPLACE "#include \"../Renderer.h\"" "#include \"Renderer.h\"" test "${probe}")
            string(REPLACE "#include \"../Renderer.cpp\"" "#include \"${CMAKE_CURRENT_SOURCE_DIR}/Renderer.cpp\"" test "${test}")
            string(REPLACE "#include \"../main.cpp\"" "#include \"pending-${control}-main.cpp\"" test "${test}")
            file(WRITE "${source}" "${test}")
            pending_frame_target(overlay_pending_frame_${control} "${source}")
        endforeach()
    endif()
endif()
