using System;
using System.IO;
using System.Text;

namespace TigerClaw.Core.Tests
{
    internal static partial class Program
    {
        private static int ExportNativeCoreCaseTable(string path)
        {
            if (File.Exists(path)) throw new IOException("Case-table output already exists");
            var output = new StringBuilder("// Generated by --native-core-case-table using .NET " + Environment.Version + ".\n" +
                "// Reproduce from the Windows reference runtime; do not hand-edit.\n#pragma once\n#include <cstdint>\n" +
                "namespace tiger::core {\nstruct CaseMapping { std::uint32_t source, target; };\n");
            foreach (bool fold in new[] { false, true })
            {
                output.Append("inline constexpr CaseMapping ").Append(fold ? "OrdinalCaseTable" : "LowerCaseTable").Append("[] = {\n");
                for (int scalar = 0; scalar <= 0x10ffff; scalar++)
                {
                    if (scalar >= 0xd800 && scalar <= 0xdfff) continue;
                    string text = char.ConvertFromUtf32(scalar);
                    string mapped = fold ? text.ToUpperInvariant() : text.ToLowerInvariant();
                    if (fold && !string.Equals(text, mapped, StringComparison.OrdinalIgnoreCase)) mapped = text;
                    if (mapped == text) continue;
                    int target = char.ConvertToUtf32(mapped, 0);
                    if (char.ConvertFromUtf32(target) != mapped) throw new InvalidOperationException("Non-scalar case mapping");
                    output.Append("    {0x").Append(scalar.ToString("x")).Append(", 0x").Append(target.ToString("x")).Append("},\n");
                }
                output.Append("};\n");
            }
            output.Append("}\n");
            File.WriteAllText(path, output.ToString(), new UTF8Encoding(false));
            Console.WriteLine("Exported case mappings from .NET " + Environment.Version);
            return 0;
        }
    }
}
