<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationManifest>..\app.manifest</ApplicationManifest>
    <LangVersion>7.3</LangVersion>
    <Nullable>disable</Nullable>
    <AssemblyName>TigerClaw.Core</AssemblyName>
    <RootNamespace>TigerClaw.Core</RootNamespace>
    <BaseOutputPath>$(MSBuildThisFileDirectory)..\_run\</BaseOutputPath>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <OutputType>WinExe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\TigerClaw.Shared\TigerClaw.Shared.csproj" />
  </ItemGroup>
</Project>
