<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <AssemblyName>TigerClaw.Core.Tests</AssemblyName>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Joint/**/*.cs" />
    <ProjectReference Include="../../next/TigerClaw.Core/TigerClaw.Core.csproj" />
  </ItemGroup>
</Project>
